### ISSUE TITLE
isPlainObject() Returns true instead of false

### ISSUE THREAD

**Issue by bharathvaj1995** [jonschlinkert/is-plain-object#11]
`isPlainObject(Object.create({})) // Returns True` I am finding conflict between your module and [this ](https://www.npmjs.com/package/is-plain-obj)module developed by Sindre Sorhus. When do you say a object is a plain object.

**Comment by jonschlinkert** [comment]
This module is correct (same as lodash and jquery). 

> When do you say a object is a plain object.

An object is "plain" when it was created by the `Object` constructor, just as it says in the description of the project. This is the generally agreed upon interpretation of a "plain object". In other words, think of it this way: "Is it an object-object, or a non-object object? Like a date or an array?" We want the former, not the latter.

> I am finding conflict between your module and this module developed by Sindre Sorhus

Sindre often copies existing modules, and to justify copying them he makes minor changes that often compromise something crucial about the module. Why? I'm not really sure, but I would guess that he knows that eventually he will get pull requests to fix whatever the problem is, which then makes his library functionally equivalent to the one he copied, without him having to do it. 

In fact, both `is-plain-object` and `isobject` were used in a certain library before Sindre was added as a maintainer. Then, right when he was added, for no reason at all, he created two new libraries, `is-obj` and `is-plain-obj`, and replaced `is-plain-object` and `isobject` with his own. Whatever his justification might be, this makes it 100% clear that he was aware of those libraries before he created his, and since he has never once attempted a pr, created an issue, or made any proactive comment to contribute to my projects or any other projects I know of, besides ones that he is a maintainer on and has control of, I can only assume his practices are predatory and self-serving. He just creates new modules with the same code as existing modules and swaps his in. IMHO, this has been a huge cause of duplicate modules and confusion in node.js, not to mention the lack of attribution and respect for copyrights and licenses. For this reason, and others, I blocked him and stopped allowing his modules in my projects about three years ago. Eventually, it will catch up with him, and I don't want the liability of that in my codebase.
